lib/anton_web/router.ex
defmodule AntonWeb.Router do
  use AntonWeb, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", AntonWeb do
    pipe_through :browser # Use the default browser stack

  end

  scope "/", AntonWeb do
    pipe_through :protected
    # Add protected routes below
    get "/", PageController, :index
    resources "/versions", VersionController
  end

  # Other scopes may use custom stacks.
  # scope "/api", AntonWeb do
  #   pipe_through :api
  # end
end

lib/anton_web/views/coherence/layout_view.ex
defmodule AntonWeb.Coherence.LayoutView do
  use AntonWeb.Coherence, :view
end

lib/anton_web/views/layout_view.ex
defmodule AntonWeb.LayoutView do
  use AntonWeb, :view

  def active?(conn, path) do

    if starts_with_path?(current_path(conn, %{}), path) do
      "active"
    else
      ""
    end
  end

  defp starts_with_path?(request_path, "/") when request_path != "/", do: false
  defp starts_with_path?(request_path, to) do
    String.starts_with?(request_path, String.trim_trailing(to, "/"))
  end

  defp render_flash(type, message) do
    ~E"""
    <div class="alert alert-<%= type %>" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    """
  end

  def show_flash(conn) do
    case get_flash(conn) do
      %{"info" => msg} ->
        render_flash("info", msg)
      %{"error" => msg} ->
        render_flash("danger", msg)
      _ ->
        ""
    end
  end

end

lib/anton_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Anton!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Anton</a>
        </div>
        <%= if AntonWeb.Coherence.ViewHelpers.logged_in?(@conn) do %>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <%= AntonWeb.Coherence.ViewHelpers.coherence_links(@conn, :layout) %>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
        <% end %>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row">

        <%= if AntonWeb.Coherence.ViewHelpers.logged_in?(@conn) do %>
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="<%= active?(@conn, "/") %>"><a href="/">Overview </a></li>
            <li class="<%= active?(@conn, "/versions") %>"><%= link("Versions", to: version_path(@conn, :index)) %></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

        <% else %>

        <div class="col-sm-9 col-md-10 main">
        <% end %>

          <%= show_flash(@conn) %>

          <main role="main">
            <%= render @view_module, @view_template, assigns %>
          </main>

        </div>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/phoenix.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/phoenix_html.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>